image: freebsd/14.x
packages:
  - ruby
  - rubygem-gems
  - rubygem-rake
  - kuzu
sources:
  - hg+https://hg.sr.ht/~ged/Ruby-Kuzu
tasks:
  - setup: |
      cd Ruby-Kuzu
      gem install --user-install -Ng
  - test: |
      export PATH=$PATH:$(ruby -r rubygems -e 'puts Gem.user_dir')/bin
      cd Ruby-Kuzu
      COVERAGE=1 rspec -cfd
